feat(profiles): Get all profiles functionality
andela/ah-lobos-backend pull request #25
Opened 2019-07-16 13:32 UTC by j4l13n

[Finishes #166789886]

#### What does this PR do?
This pull request adds resources that allow users to: 
- add get all profiles method
- add the get all profiles route
- add test of get all method

#### Description of Task to be completed?

#### How should this be manually tested?
Follow instructions on the `README.md` file attached to this repo to set up the project on your local machine.
Make sure that you have added all environment variables using `example.env`
- Run the application
```
> npm run dev
```

Access the following routes to test

> `/api/profiles` to get all profiles when you have logged in 

Test using Heroku links (click to the link to test):

[Heroku link](https://ah-lobos-backend-swagger.herokuapp.com/#/profile/get_api_profiles)

#### Any background context you want to provide?
- user must be logged in to view authors profiles
#### What are the relevant pivotal tracker stories?
[#166789886](https://www.pivotaltracker.com/story/show/166789886)
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/31614647/61298578-c5864480-a7de-11e9-84de-36266b72beef.png)
![image](https://user-images.githubusercontent.com/31614647/61298609-d3d46080-a7de-11e9-8477-4aa0db5fccbc.png)

#### Questions:
- N/A

2019-07-16 13:50 UTC, adafia approved these changes

2019-07-16 13:50 UTC, Emile-Nsengimana approved these changes

2019-07-16 13:50 UTC, manzif approved these changes

2019-07-16 18:35 UTC, emukungu commented
add code climate maintainability to your task for the product.

2019-07-16 18:52 UTC, emukungu requested changes

2019-07-16 18:52 UTC, emukungu commented on src/controllers/profileController.js
> +        profile: findUsers
instead of profile, let your return indicate 'users'

2019-07-16 18:52 UTC, emukungu commented on src/controllers/profileController.js
> +  static async getAllProfiles(req, res) {
change the name to be more descriptive to your task; you are returning a list of users with their profiles

2019-07-16 18:54 UTC, emukungu commented
where are the mockups?

2019-07-16 19:07 UTC, j4l13n commented
> where are the mockups?

I needed your feedback on what I have done, and I am working on I will finish them by tomorrow.

2019-07-16 19:40 UTC, emukungu commented
look into the maintainability issue as well. let's change it from C to A

2019-07-16 19:48 UTC, j4l13n commented
> look into the maintainability issue as well. let's change it from C to A

I did not get this message sorry, 

> look into the maintainability issue as well. let's change it from C to A

Okay, let me work on it

2019-07-17 11:29 UTC, Dom58 approved these changes

2019-07-18 06:31 UTC, merged