chore(coveralls): Integrate coveralls
andela/ah-lobos-backend pull request #5
Opened 2019-06-25 11:26 UTC by Dom58

- I have just created a file called .covellals.yml to keep the private key
- I modify a readme file to add a coveralls rate badge

[Maintains #166789865]

2019-06-25 12:31 UTC, Emile-Nsengimana reviewed
I think you have to check the readme on `ch-integrate-coveralls-#166789865` not on `develop`!

2019-06-25 13:27 UTC, Emile-Nsengimana approved these changes

2019-06-26 06:27 UTC, j4l13n approved these changes

2019-06-26 08:17 UTC, emukungu requested changes
- fix the new line issue
- add screen shots of the badge

2019-06-26 18:16 UTC, merged