#166789859 Configure postgres database using sequelize
andela/ah-lobos-backend pull request #8
Opened 2019-06-25 16:33 UTC by adafia

#### What does this PR do?
This pull request adds posgresql configuration with `Sequelize`. 
#### Description of Task to be completed?
N/A
#### How should this be manually tested?

> install dependencies and development dependencies
```
> npm install
```

> create database to postgresql
```
> createdb authorsHavenDb
```
remember to change the password in config.json file for development

> create your config file
```
> create config.json file into 'config/' and add same data as 'example.config.json' 
remember to change database user, and password
```

> add table to database

```
> sequelize db:migrate
```
The above command will migrate all table to your database

#### Any background context you want to provide?
The initial codebase was setup with MongoDb

#### What are the relevant pivotal tracker stories?
[#166789859](https://www.pivotaltracker.com/story/show/166789859)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2019-06-25 18:30 UTC, Emile-Nsengimana reviewed
- I think that description of Task to be completed has to be there as long as you are raising a PR for a finished task?
- and also it will be better if we use a .env file for our configuration so that each one of us doesn't have to make unnecessary changement

2019-06-26 06:20 UTC, j4l13n approved these changes

2019-06-26 06:25 UTC, manzif approved these changes

2019-06-26 06:36 UTC, Dom58 reviewed
Please, leave a new blank line to every file

2019-06-26 08:23 UTC, emukungu requested changes
use a .env file for the config as requested by @Emile-Nsengimana for the whole project.

2019-06-26 13:15 UTC, emukungu commented on config/config.js
> +module.exports = config;
add a new line

2019-06-27 06:56 UTC, merged